### ISSUE TITLE
Aging-report results are incorrect

### ISSUE THREAD

**Issue by DanielInfu** [Keeper-Security/Commander#1065]
Using the aging-report command to see which passwords need to be changed since March13th. 

Command run:
aging-report --rebuild --period 124d 
aging-report --period=142d --format=csv --output=Report.csv

Result file confirms: Aging Report: Records With Passwords Last Modified Before 2023/03/13

However data presented in report does not match actual data in Vault, many of the items have had password changes in the monthds after march but the "Last password changed" matches the created record date not the password changed date.
![KeeperVault](https://github.com/Keeper-Security/Commander/assets/141241374/ab01eaf1-892e-4731-8909-ee9839116e4c)
![Keeper-Report](https://github.com/Keeper-Security/Commander/assets/141241374/a30b0b22-545e-4387-a5d6-0f1e77397526)

**Comment by aaunario-keeper** [comment]
Hi,

The issue you're seeing was supposed to have been addressed in one of Commander's relatively recent releases, so there's a good possibility that what you're seeing is simply the result of using an outdated version of Commander.

That said, can you please make sure that you have the latest version of Commander (16.9.11) by running the following command in the Commander shell:
`version -v`
and checking the value of the "Commander Version" field in the resulting output? 

If your version isn't the latest, you can update Commander -- depending on how you installed it in the first place -- by using pip (`pip install -U keepercommander`), by downloading the appropriate binaries/source code from https://github.com/Keeper-Security/Commander/releases, or via `git pull` if you're running Commander via a local clone of our Github repository.

**Comment by aaunario-keeper** [comment]
Upon further investigation, it appears as though the record-history data local-caching mechanism for that command isn't working properly at the moment. We certainly appreciate you bringing this issue to our attention, and rest assured, we will be working towards getting a fix out ASAP in an upcoming release. I'll make sure to keep you updated when that occurs.

In the meantime, however, here's a work-around you can do that should provide a more accurate report:
1) Within Commander working directory (which can be found by using the command `version -v` and inspecting the value of the " Working directory" field in the output), delete any files with the extension ".db" (`rm *.db` should work for any *NIX command-line)
2) Run `aging-report` again (remember to export the resulting data to an external CSV or JSON file)

Re: the above work-around, please keep in mind that (until this particular bug has been addressed) you'll have to delete the associated local cache (*.db file) every time before you run the `aging-report` command in order to get an accurate report.

Thanks again for your invaluable input, which should prove immensely useful in helping us improve our product.

**Comment by DanielInfu** [comment]
Hello again,

I am on windows and found it in a .keeper sub directory (sox_<Number>.db), I have deleted and re-ran the report.    I am getting better results but there are still some items that show incorrectly, for example I have one record created on 2/23/23 and the password was updated on 6/2/23 but it's still showing up on the list with the initial creation date.  Let me know if you want me to open a support ticket and we can schedule a troubleshooting session.

**Comment by aaunario-keeper** [comment]
Hi,

This issue has been addressed in the latest Commander release (version 16.9.13, released about an hour prior to the time of this message). 

Please install/update to the latest version of Commander (using one of the methods I described in a previous message in this thread) and let us know if the problem persists.

Thanks.
